apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: invalid-namespace
spec: {}
status: {}

opa-gatekeeper/valid-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: valid-namespace
  labels:
    gatekeeper: test
